### ISSUE TITLE
First start validates the pihole but gives an error

### ISSUE THREAD

**Issue by kongo09** [sterrenburg/flutterhole#103]
**Describe the bug**
I start the app for the first time, setup my pihole, validate and all is green. The dashboard however shows an error:

{message: fetchSummary failed with unexpected error, error: type '_OneByteString' is not a subtype of type 'int' in type cast}

**To Reproduce**
1. See above

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Pi-hole version: 4.3.1
 - FlutterHole version: 5.1.2

**Additional context**

**Comment by sterrenburg** [comment]
Hello @kongo09 👋 - Thanks for opening an issue!

The Pi-hole API has had some changes since V5, as a result FlutterHole only supports Pi-hole V5+. 

It seems that the error you are getting is the result of this version mismatch (i.e. Pi-hole version 4.3.1). I suggest upgrading you Pi-hole if possible. Hope this helps.

**Comment by kongo09** [comment]
Thanks, I did the update to 5.0 and more it works.

Thomas <notifications@github.com> schrieb am So., 21. Juni 2020, 15:10:

**Comment by kongo09** [comment]
Thanks, I did the update to 5.0 and now it works
