### ISSUE TITLE
resource mipmap/launcher_icon not found

### ISSUE THREAD

**Issue by Rudloff** [sterrenburg/flutterhole#29]
Hello,

When building 1.0.0 with flutter 1.3.2, it fails with this error:
```
Execution failed for task ':app:processReleaseResources'.

> Android resource linking failed

  /home/pierre/www/fdroiddata/build/sterrenburg.github.flutterhole/build/app/intermediates/merged_manifests/release/AndroidManifest.xml:25: AAPT: error: resource mipmap/launcher_icon (aka sterrenburg.github.flutterhole:mipmap/launcher_icon) not found.



  error: failed processing manifest.
```

**Comment by sterrenburg** [comment]
Hi, in my own CI script on Codemagic, I run this Flutter package to generate the correct icons:
```
flutter packages pub run flutter_launcher_icons:main
```
Would you rather I commit the generated images to the repository, or do you want to run the generation on the Fdroid side?

**Comment by Rudloff** [comment]
I added that to our build recipe and now it builds correctly. Thanks for your help!

**Comment by desktopukr** [comment]
Running Gradle task 'assembleDebug'...                            304.1s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                 8.6s
E/AndroidRuntime(10733): FATAL EXCEPTION: main
E/AndroidRuntime(10733):        at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime(10733):        at android.app.ActivityThread.main(ActivityThread.java:8250)E/AndroidRuntime(10733):        at java.lang.reflect.Method.invoke(Native Method)E/AndroidRuntime(10733):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)E/AndroidRuntime(10733):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
E/AndroidRuntime(10733): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pnn.pos.MainActivity" on path: DexPathList[[zip file "/data/app/~~Fi1LoYac4OgsqsQun8xE_Q==/com.pnn.pos-CV_rGXXjYsQwX2NiFn0nQg==/base.apk"],nativeLibraryDirectories=[/data/app/~~Fi1LoYac4OgsqsQun8xE_Q==/com.pnn.pos-CV_rGXXjYsQwX2NiFn0nQg==/lib/arm64, /data/app/~~Fi1LoYac4OgsqsQun8xE_Q==/com.pnn.pos-CV_rGXXjYsQwX2NiFn0nQg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(10733):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(10733):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(10733):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(10733):        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(10733):        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
E/AndroidRuntime(10733):        at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
E/AndroidRuntime(10733):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3652)
E/AndroidRuntime(10733):        ... 12 more
