### ISSUE TITLE
HTTP status error 400

### ISSUE THREAD

**Issue by modem7** [sterrenburg/flutterhole#49]
Setup: Reverse proxy (nginx) into pihole. 
Last time it worked: previous version

URL: user:pass@host
Port: 443

![20190801_144015](https://user-images.githubusercontent.com/4349962/62308560-70545f00-b47d-11e9-927b-d1e8d1b83a86.jpg)
![Screenshot_20190801-143907](https://user-images.githubusercontent.com/4349962/62308561-70ecf580-b47d-11e9-8db0-7fd0ae5db8cb.jpg)

Manually going to the URL works as expected. No deviations from previous setup.

**Comment by oakkitten** [comment]
apparently flutterhole sends http traffic to a https port. not sure how i could specify that the connection should be secure. there's an option for self-signed certificates though?..

    [info] 21106#0: *33 client sent plain HTTP request to HTTPS port while reading client request headers, client: 1.2.3.4, server: server.com, request: "GET /admin/api.php?versions= HTTP/1.1", host: "server.com:443"

**Comment by sterrenburg** [comment]
I will preface this by saying that I test on a virtual local network without SSL and reverse proxy, so the testing on this is spotty.

So I tried to tackle the proxy user/pass combination by implementing the `Proxy-Authorization` header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization). This way, the credentials aren't shown in the URI string but instead used in a HTTP header.

Example of how to add the header in Dart: https://stackoverflow.com/questions/50244416/how-to-pass-basic-auth-credentials-in-api-call-for-a-flutter-mobile-application.

Seems like this isn't the solution for you guys. Do you know if the only way to use the proxy, is by using the plaintext credentials in the URI (e.g. `https://username:password@proxy.host:proxy.port')?

**Comment by modem7** [comment]
Whatever you did on the latest update, definitely fixed it!

Thank you!

**Comment by sterrenburg** [comment]
> apparently flutterhole sends http traffic to a https port. not sure how i could specify that the connection should be secure. there's an option for self-signed certificates though?..
> 
> ```
> [info] 21106#0: *33 client sent plain HTTP request to HTTPS port while reading client request headers, client: 1.2.3.4, server: server.com, request: "GET /admin/api.php?versions= HTTP/1.1", host: "server.com:443"
> ```
> 
> Edit: it seems that the code mentions some "useSSL" variable, but I don't see anything like it in the UI?

The master branch is deployed to the beta branch in Google Play, the most recent Beta release contains a toggle for using SSL. If you are on the Beta Program, please update and let me know if it works!

Glad you got it working @modem7, I will keep an eye out for the proxy implementation.

**Comment by oakkitten** [comment]
for me, this problem is not related to the basic auth at all since i'm not using it. also i'm not using reverse proxies, as i run php directly in nginx. 

the problem is that the application is connecting to `http://server.com:443`. this should be `https`.

> So I tried to tackle the proxy user/pass combination by implementing the Proxy-Authorization header (...). This way, the credentials aren't shown in the URI string but instead used in a HTTP header.

i'm not sure what proxies have to do with anything here. to a client (flutterhole), the reverse proxies appear just like normal servers. it shouldn't care about them.

as for the authentication, the browsers will convert `http://foo:bar@baz` to a `GET /` request, then after getting a 401 they will repeat the same requst adding the credentials (`foo:bar`) into the headers as `Authorization: Basic HeXsTrInG`, as described in your SO link.

as you can convert the hex string back to the credentials, having the password in the url is no less or more secure than manually making the header. i belive the issue in #42 is that when you open the settings, the password is displayed in plain text on screen. something like masking it with ***s would work just as well.
