### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by Gorillab1scuit** [sterrenburg/flutterhole#77]
I'm getting an authentication error even though I'm authenticated with API. The Query total and blacklist data is there.

![Screenshot_20200516-004645](https://user-images.githubusercontent.com/36890827/82110802-e70dd080-970e-11ea-979a-6f0328455779.png)

**Comment by sterrenburg** [comment]
Hello @Gorillab1scuit  👋 - Thanks for opening an issue!

Could you check the API Log and look for requests that provide a `Query Parameter` called `auth`? This information can be found by clicking an entry, then navigating to the 'Request' tab. The value of the `auth` parameter should be the plaintext API token that you scanned from your Pi-hole.

Alternatively, try going to this URL in a browser with your own credentials:

`{{ base_url  }}?topItems&auth={{ auth  }}`

Does this yield a JSON response with some data, or an empty response looking like `[]`?

**Comment by Gorillab1scuit** [comment]
There are no auth references in the few API logs in flutterhole. I can
navigate to the webpage successfully with the URL provided, and the
response is a total queries over 24 graph.

**Comment by sutch** [comment]
I am experiencing the same issue.

> Could you check the API Log and look for requests that provide a `Query Parameter` called `auth`? This information can be found by clicking an entry, then navigating to the 'Request' tab. The value of the `auth` parameter should be the plaintext API token that you scanned from your Pi-hole.

No requests contain an `auth` parameter.  The parameters are empty or contain parameters named status, summaryRaw, or overTimeData10mins.

> Alternatively, try going to this URL in a browser with your own credentials:
> 
> `{{ base_url }}?topItems&auth={{ auth }}`
> 
> Does this yield a JSON response with some data, or an empty response looking like `[]`?

This returns a JSON response containing top_queries and top_ads, each containing 10 entries.

**Comment by gorillap** [comment]
This is likely related to the recent 5.0 update.
Mine did the same thing. 

Try clearing the apps storage/data, Reconfigure your pihole. Try using the IP address instead of URL if you have an issue, i.e. http://192.168.1.xxx
I did this and got basic functionality/stats showing but live query log is still not working

**Comment by sterrenburg** [comment]
I've heard of more people needing to clear their storage/cache after updating from the 2.x version, so that might be a good fallback attempt to fix the issue.

The 5.x version of the app is basically a new package under the same name. Perhaps this leads to some kinks wrt the app's OS permissions.

On the Pihole form page, do you guys see your API token in the field after saving and reloading? Perhaps the form data isn't properly saved.

**Comment by sutch** [comment]
I cleared storage for flutterhole, re-scanned the API token from Pi-hole, and the problem is now resolved. Thank you for the suggestion.

Initially after updating to the 5.x version of the app, the API token was missing and I had to re-scan the API token from Pi-hole. This did not fix the issue. Clearing the storage and then adding the token was what worked for me.

**Comment by Gorillab1scuit** [comment]
no change for me, unfortunately. I couldn't remove my old pihole.  Had to
reboot, then the config was gone.  Set it back up and still not
authenticated for the bottom 2 graphs on the dashboard.

~ Matt
347.416.NERD
get Gmail @ http://mail.google.com

**Comment by Gorillab1scuit** [comment]
OK, I deleted the config for my pi-hole. It left Pi-hole #0.  I added the
API config and BOOM it works.

~ Matt
347.416.NERD
get Gmail @ http://mail.google.com
