### ISSUE TITLE
v5 - No Authentication needed

### ISSUE THREAD

**Issue by abacao** [sterrenburg/flutterhole#79]
Flutterhole doesn't show some data if pihole doesn't have a password and without token set in app. 

This if fixed by setting the api token as "No password set" without quotes.

With this, Flutterhole has more data but it can't (for example) pause the pihole (error occurs).

Suggestion: if no token is set, use the token "No password set" to show all data in app and try to fix the error when trying to pause pihole action.

**Comment by sterrenburg** [comment]
Hello @abacao 👋 - Thanks for opening an issue!

I wasn't aware this was possible, thank you for the suggestion. Sounds like something that can be implemented.

Currently, if no API token is set, no request is sent and a `NotAuthenticatedPiException` is thrown.

In order to prevent confusion regarding when/when not to use an API token, would it be an idea to add a checkbox saying something like "This Pi-hole has no password"? Enabling this could disable the API token input field.

**Comment by abacao** [comment]
Yes, the creation of a feature that enables the "no password" box may be a better approach if pihole changes the flow.
