### ISSUE TITLE
stuck on loading screen

### ISSUE THREAD

**Issue by SSTGIO** [sterrenburg/flutterhole#86]
**Describe the bug**
After the latest update to v5.0.125 build 625 flutterhole fails to display any information on the dashboard Summary, Domains, and Clients pages. All that is displayed is the four blue dots spinning. I have left the app running for about 10 minutes  and still no information is displayed. I have deleted and reapplied my API Key and reapplied it, Uninstaller and reinstalled the APP. I have saved and validated the API each time.  I have restarted my phone. I cannot get any information to display. 
Prior to this update your APP worked flawlessly and displayed my PiHoles data accordingly.

**Comment by sterrenburg** [comment]
Hello @SSTGIO 👋 - Thanks for opening an issue!

Sorry to hear that. I have heard reports from other users about similar problems, so you are not alone. A few things come to mind that might help us out:

- Try clearing the app data/cache from the app settings;
- Try reloading the Pi-hole configurations using the dropdown  menu on the "My Piholes" page;
- Try _deleting_ the Pi-hole configurations using the dropdown  menu on the "My Piholes" page;
- If you are using as domain in the Base URL (e.g. "http://pi.hole"), try swapping it out with the IP address (e.g. 10.0.1.2);
- Does the "API log" page show any HTTP requests being made?

Note to self: implement some timeout duration so that requests don't hang indefinitely.

**Comment by SSTGIO** [comment]
Issue has been fixed once I upgraded to newest version. Now your fantastic APP is displaying all data.
